from setuptools import find_packages, setup

setup(
    name='src',
    packages=find_packages(),
    version='0.1.0',
    description='A hybrid summarization model for emails, trained on synthetic datasets generated by ensemble methods.',
    author='Arkishman Ghosh',
    license='',
)
